### ISSUE TITLE
Empty bounding boxes

### ISSUE THREAD

**Issue by NameSiege** [Karang/mineflayer-pathfinder#16]
Should the pathfinder break something with an empty bounding box? Such as wheat or a sapling. I know you can add avoidance, but that prevents the bot from standing on the block.

You can add this right after line 224 in index.js:
`if ((bot.blockAt(new Vec3(b.x, b.y, b.z), false).boundingBox == "empty")) {
    digging = false
    return
}`

**Comment by Karang** [comment]
If you don't want the bot to break a certain block, you have to add it to the break exclusion list: https://github.com/Karang/mineflayer-pathfinder/blob/master/lib/movements.js#L27

**Comment by NameSiege** [comment]
Sorry, should have been more clear. I've already tried that before, but just to be safe I tried it again.
`	this.blocksCantBreak.add(mcData.blocksByName.wheat.id)
`
[https://streamable.com/myxkz4](url)

**Comment by Karang** [comment]
Well that's seems to be working fine: it doesn't break the block. What do you want it to do ?

**Comment by NameSiege** [comment]
Damn I feel stupid...

**Comment by Karang** [comment]
> Damn I feel stupid...

I'm not blaming you :) This part is not very well documented
