### ISSUE TITLE
Keeps spamming 0 moves and duplicating pathing, ending up in not being able to move and triggering anti cheat alerts and crashing after a long amount of time.

### ISSUE THREAD

**Issue by skyrawr** [Karang/mineflayer-pathfinder#2]
MleBrhXzmM: I can get there in 0 moves. Computation took 100.24 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.38 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.38 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.07 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.07 ms.
JHEORFlJzR: I can get there in 20 moves. Computation took 100.68 ms.
JHEORFlJzR: I can get there in 20 moves. Computation took 100.68 ms.
JHEORFlJzR: I can get there in 20 moves. Computation took 100.68 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 0.20 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 0.20 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 106.18 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 106.18 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.49 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.49 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 0.19 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 0.19 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.27 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.27 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.07 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.07 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 101.83 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 101.83 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 101.04 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 101.04 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.29 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.29 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.29 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.29 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.46 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.46 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 106.42 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 106.42 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 0.19 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 0.19 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.39 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.39 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 104.44 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 104.44 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.11 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.11 ms.
JHEORFlJzR: I can get there in 21 moves. Computation took 100.07 ms.
JHEORFlJzR: I can get there in 21 moves. Computation took 100.07 ms.
JHEORFlJzR: I can get there in 21 moves. Computation took 100.07 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 0.17 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 0.17 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.14 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.14 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.80 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.80 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 0.19 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 0.19 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 101.57 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 101.57 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.49 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.49 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.08 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.08 ms.
JHEORFlJzR: I can get there in 19 moves. Computation took 107.03 ms.
JHEORFlJzR: I can get there in 19 moves. Computation took 107.03 ms.
JHEORFlJzR: I can get there in 19 moves. Computation took 107.03 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.19 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.19 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 0.28 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 0.28 ms.
JHEORFlJzR: I can get there in 20 moves. Computation took 100.73 ms.
JHEORFlJzR: I can get there in 20 moves. Computation took 100.73 ms.
JHEORFlJzR: I can get there in 20 moves. Computation took 100.73 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.07 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.07 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 0.26 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 0.26 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.61 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.61 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.47 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.47 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 109.34 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 109.34 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 0.30 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 0.30 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.11 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.11 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.38 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.38 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 105.34 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 105.34 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 0.17 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 0.17 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.15 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.15 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.27 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.27 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.24 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 100.24 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 0.28 ms.
MleBrhXzmM: I can get there in 0 moves. Computation took 0.28 ms.

the strings before "I can get..." are the bot's names btw

**Comment by skyrawr** [comment]
update. the bots crashed, they got to 5400 blocks.

**Comment by Karang** [comment]
What server ? What code ? If it triggered the anticheat it's probably because of mineflayer's physic, it is a known issue and need to be improved.

**Comment by skyrawr** [comment]
I tried it on a vanilla server, they keep duplicating trying to path multiple times at the same times, resulting in the bot moving wrongly and being teleported back, then it starts spamming "moves 0" while still trying to move

**Comment by Karang** [comment]
What do you mean by "duplicating" ? Do you have the same issue with only 1 bot ? Can you share a minimal code that can reproduce the issue ?

**Comment by skyrawr** [comment]
I think it was duplicating paths because i did it on the spawn event, oops. basically it was path finding multiple times
