### ISSUE TITLE
Callback upon goal reached

### ISSUE THREAD

**Issue by Garfield100** [Karang/mineflayer-pathfinder#25]
I know the mineflayer stuff is more event-based but being able to set a callback would be very useful to more easily string together actions.
It's very easy to add to the `inject` function. Should I make a pull request?

**Comment by Karang** [comment]
The dynamic goals can emit the goal_reached event multiple time, that would not fit well with callbacks. The choice of using events was made to work with all types of goals.

It is easy enough to wrap the function in a callback:
```js
function gotoGoalCallback(goal, callback) {
  bot.pathfinder.setGoal(goal)
  bot.once('goal_reached', callback)
}
```

**Comment by Garfield100** [comment]
Forgive me, I was unaware that `.once` could be used like that. That actually makes all of mineflayer a lot easier 😅
thank you
