### ISSUE TITLE
np from getPositionOnTopOf can be null and causes crash

### ISSUE THREAD

**Issue by Slord6** [Karang/mineflayer-pathfinder#26]
This section of `monitorMovement`

https://github.com/Karang/mineflayer-pathfinder/blob/0aaee90102c7cbc030aa3a1ec350608eae0b8d53/index.js#L214-L220

can result in `np` being null, even after the 'if null' check and assignment on line 216.

It seems to be fixed by moving the use of `np` further down to here:

https://github.com/Karang/mineflayer-pathfinder/blob/0aaee90102c7cbc030aa3a1ec350608eae0b8d53/index.js#L270-L274

presumably because the instances where np is null is only true for the digging or placement sections (I think specifically the issue is with air blocks). Happy to put in a PR but want to check I'm on the right lines before I make any changes

**Comment by Karang** [comment]
Did you encounter cases where this happen to be null ? It shouldn't happen as it would mean the block bellow a target position is non physical (air) and that should be impossible according to the movement generation rules.

**Comment by Slord6** [comment]
Yes, only when the bot was trying to go up. It only happens when the bot has blocks to place in its inventory.
The simplest setup using the `test.js` example is this:
```
[pf]
[x]
[x] [bf]  
```
x = dirt block
pf = player feet
bf = bot feet
Where the bot has a few dirt blocks in its inventory

**Comment by Karang** [comment]
Indeed. The fix you suggested was also the correct one (commited)

**Comment by Slord6** [comment]
Great, thanks. Have you tested that fix when you're the opposite side of a river from the bot, so it has to swim to you? I applied that fix locally but was still getting it occasionally crashing and it seemed like swimming was the link between them. I'll try and repro tomorrow if you're not seeing it.

**Comment by Karang** [comment]
> Great, thanks. Have you tested that fix when you're the opposite side of a river from the bot, so it has to swim to you? I applied that fix locally but was still getting it occasionally crashing and it seemed like swimming was the link between them. I'll try and repro tomorrow if you're not seeing it.
> 
> Edit: definitely still happens on some occasions. It's when the bot is swimming or just about to swim I think.

Should be solved in 1.0.9
