### ISSUE TITLE
enable github action for CI

### ISSUE THREAD

**Issue by rom1504** [Karang/mineflayer-pathfinder#5]
I advise the recommended github action for CI for node (just go to action tab, you'll see it), it's simple and it works

**Comment by Karang** [comment]
thanks, done

**Comment by rom1504** [comment]
I see you added the publish action, which is nice!
but there is also an action for ci, which is good here at least for lint even if there are no tests, see https://github.com/PrismarineJS/prismarine-world/blob/master/.github/workflows/nodejs.yml for example 
(also see reference in https://github.com/actions/starter-workflows/blob/87a8d83e309a179bf1d126a21cb7669c830b0e0e/ci/node.js.yml )

**Comment by Karang** [comment]
> I see you added the publish action, which is nice!
> but there is also an action for ci, which is good here at least for lint even if there are no tests, see https://github.com/PrismarineJS/prismarine-world/blob/master/.github/workflows/nodejs.yml for example
> (also see reference in https://github.com/actions/starter-workflows/blob/87a8d83e309a179bf1d126a21cb7669c830b0e0e/ci/node.js.yml )

done
